language: node_js
node_js:
  - "0.10.26"
before_script:
  - npm install
  - npm install -g gulp
install:
  - npm install -g codecov
script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d7532d96e0012e71442
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
    after_success:
      - bash <(curl -s https://codecov.io/bash)
